name: Continuous Integration and Delivery with Github Actions

on:
  push:
    branches:
    - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_ACCESS_TOKEN }}

    - name: Login to Google Cloud Platform
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: ${{ secrets.GOOGLE_CREDENTIALS }}

    - name: Configure Google Cloud SDK Repository
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates gnupg curl
        curl -fsSL https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor > /usr/share/keyrings/cloud.google.gpg
        echo "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main" | sudo tee /etc/apt/sources.list.d/google-cloud-sdk.list > /dev/null
        sudo apt-get update

    - name: Install GKE Cloud Auth Plugin
      run: sudo apt-get install -y google-cloud-sdk-gke-gcloud-auth-plugin

    - name: Configure GKE Cloud Auth Plugin
      run: echo "export USE_GKE_GCLOUD_AUTH_PLUGIN=True" >> $GITHUB_ENV

#    - name: Configure AWS credentials
#      uses: aws-actions/configure-aws-credentials@v4
#      with:
#        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

#    - name: Login to Amazon ECR
#      id: login-ecr
#      uses: aws-actions/amazon-ecr-login@v2

    - name: Configure GKE Cluster Access
      run: gcloud container clusters get-credentials vale-cluster --region northamerica-northeast1 --project ${{ secrets.PROJECT_ID }}

    - name: Configure Docker Authentication for Google Cloud Artifact Registry
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Setup Java 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
        cache: maven

    - name: Build Application .jar
      working-directory: ./rest-with-spring-boot-and-java
      run: mvn clean package -DskipTests

    - name: Docker Compose Build
      run: docker compose build
#
#    - name: Tag and Push to Docker Image to Amazon Container Registry - ECR
#      run: |
#        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.IMAGE_REPO_URL }}:latest
#        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
#
#        docker push ${{ secrets.IMAGE_REPO_URL }}:latest
#        docker push ${{ secrets.IMAGE_REPO_URL }}:${{ github.run_id }}
#
#    - name: Download task definition
#      run: |
#        aws ecs describe-task-definition --task-definition ${{ secrets.TASK_DEFINITION_NAME }} --query taskDefinition > task-definition.json
#
#    - name: Fill in the new image ID in the Amazon ECS task definition
#      id: task-def
#      uses: aws-actions/amazon-ecs-render-task-definition@v1
#      with:
#        task-definition: task-definition.json
#        container-name: ${{ secrets.CONTAINER_NAME }}
#        image: ${{ secrets.IMAGE_REPO_URL }}:latest
#
#    - name: Deploy Amazon ECS task definition
#      uses: aws-actions/amazon-ecs-deploy-task-definition@v2
#      with:
#        task-definition: ${{ steps.task-def.outputs.task-definition }}
#        service: ${{ secrets.SERVICE_NAME }}
#        cluster: ${{ secrets.CLUSTER_NAME }}
#        wait-for-service-stability: true

    - name: Push to Google Cloud Artifact Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.REGISTRY_INFO }}/${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.REGISTRY_INFO }}/${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        
        docker push ${{ secrets.REGISTRY_INFO }}/${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
        docker push ${{ secrets.REGISTRY_INFO }}/${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}

#    - name: Deploy to Google Cloud Run
#      run: |
#        gcloud run deploy rest-with-spring-boot \
#        --image ${{ secrets.REGISTRY_INFO }}/${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest \
#        --region us-central1 \
#        --platform managed \
#        --allow-unauthenticated

    - name: Deploy to GKE
      run: |
        kubectl set image deployment/rest-with-spring-boot rest-with-spring-boot=${{ secrets.REGISTRY_INFO }}/${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        kubectl rollout status deployment rest-with-spring-boot

    - name: Push to Docker Hub Container Registry
      run: |
        docker tag ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
        
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/rest-with-spring-boot:${{ github.run_id }}
